#!/bin/bash

file=$1

if [[ $file == "" ]] || [[ $file == "-h" ]]; then 
    if [[ ! -z "$SHORT_HELP_MODE" ]]; then
        echo "like tee, remove colors escape codes before writing to file"
        exit 1
    fi

    cat <<EOF
$0 <file>

like tee but removes colors escape codes from the input stream before logging it to the <file>
leaves stdout unaltered.

EOF
    exit 1
fi


tee >(sed 's/\x1b\[[0-9;]*m//g' >${file})


